### PR TITLE
get rid of global and use forEach instead of map

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Please use `npm version minor/patch` etc when publishing new versions so they are tagged in git :)

**Comment by heapwolf** [comment]
``` bash
$npm owner add ralphtheninja level-2pc
+ ralphtheninja (level-2pc)
```

**Comment by ralphtheninja** [comment]
_grins_

**Comment by ralphtheninja** [comment]
```
$ npm publish
+ level-2pc@5.2.3
```

**Pull request merged**
