### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Current version on npm is `5.4.1`, current version in package.json is `5.4.2` but not published to npm yet. Should we skip that version and publish this as `5.4.3`?

**Comment by ekristen** [comment]
We really need to ensure that these version bumps especially the ones with major bumps does not break the library.

**Comment by ralphtheninja** [comment]
@ekristen That's why we have tests. Are there things in the tests that we aren't checking for that needs to be implemented to ensure this?

**Comment by ralphtheninja** [comment]
Creating new PR on separate internal branch.

**Comment by ralphtheninja** [comment]
https://github.com/hij1nx/level-2pc/pull/12

**Comment by ekristen** [comment]
@ralphtheninja honestly the tests should be **good** enough to verify it is working, but might be worth some extra tests just to be sure.

**Pull request closed without merging**
